import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useLanguage } from '@/contexts/LanguageContext';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { toast } from '@/hooks/use-toast';
import { Send, FileText, Lightbulb } from 'lucide-react';

const complaintSchema = z.object({
  type: z.enum(['complaint', 'suggestion']),
  category: z.string().min(1, 'Kategori diperlukan'),
  subject: z.string().min(5, 'Subjek mestilah sekurang-kurangnya 5 aksara').max(200),
  description: z.string().min(20, 'Keterangan mestilah sekurang-kurangnya 20 aksara').max(2000),
  priority: z.enum(['low', 'normal', 'high', 'urgent']).optional(),
});

type ComplaintFormData = z.infer<typeof complaintSchema>;

const categories = [
  { value: 'welfare', labelMs: 'Kebajikan', labelEn: 'Welfare' },
  { value: 'facilities', labelMs: 'Kemudahan', labelEn: 'Facilities' },
  { value: 'hr', labelMs: 'Sumber Manusia', labelEn: 'Human Resources' },
  { value: 'finance', labelMs: 'Kewangan', labelEn: 'Finance' },
  { value: 'safety', labelMs: 'Keselamatan', labelEn: 'Safety' },
  { value: 'others', labelMs: 'Lain-lain', labelEn: 'Others' },
];

interface ComplaintFormProps {
  onSuccess: () => void;
}

export function ComplaintForm({ onSuccess }: ComplaintFormProps) {
  const { t, language } = useLanguage();
  const { user } = useAuth();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const {
    register,
    handleSubmit,
    setValue,
    watch,
    reset,
    formState: { errors },
  } = useForm<ComplaintFormData>({
    resolver: zodResolver(complaintSchema),
    defaultValues: {
      type: 'complaint',
      priority: 'normal',
    },
  });

  const selectedType = watch('type');

  const onSubmit = async (data: ComplaintFormData) => {
    if (!user) {
      toast({
        title: language === 'ms' ? 'Ralat' : 'Error',
        description: language === 'ms' ? 'Sila log masuk terlebih dahulu' : 'Please log in first',
        variant: 'destructive',
      });
      return;
    }

    setIsSubmitting(true);
    try {
      const { error } = await supabase.from('complaints').insert({
        type: data.type,
        category: data.category,
        subject: data.subject,
        description: data.description,
        priority: data.priority || 'normal',
        submitted_by: user.id,
        reference_number: '', // Will be generated by trigger
      });

      if (error) throw error;

      toast({
        title: language === 'ms' ? 'Berjaya!' : 'Success!',
        description: language === 'ms' 
          ? 'Aduan/cadangan anda telah dihantar. Sila simpan nombor rujukan anda.'
          : 'Your complaint/suggestion has been submitted. Please save your reference number.',
      });
      reset();
      onSuccess();
    } catch (error: any) {
      toast({
        title: language === 'ms' ? 'Ralat' : 'Error',
        description: error.message,
        variant: 'destructive',
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Send className="w-5 h-5 text-primary" />
          {language === 'ms' ? 'Hantar Aduan / Cadangan' : 'Submit Complaint / Suggestion'}
        </CardTitle>
        <CardDescription>
          {language === 'ms' 
            ? 'Isi borang di bawah untuk menghantar aduan atau cadangan anda kepada MBJ.'
            : 'Fill in the form below to submit your complaint or suggestion to MBJ.'}
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          {/* Type Selection */}
          <div className="space-y-3">
            <Label>{language === 'ms' ? 'Jenis' : 'Type'}</Label>
            <RadioGroup
              defaultValue="complaint"
              onValueChange={(value) => setValue('type', value as 'complaint' | 'suggestion')}
              className="flex gap-4"
            >
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="complaint" id="complaint" />
                <Label htmlFor="complaint" className="flex items-center gap-2 cursor-pointer">
                  <FileText className="w-4 h-4 text-destructive" />
                  {t('complaints.complaint')}
                </Label>
              </div>
              <div className="flex items-center space-x-2">
                <RadioGroupItem value="suggestion" id="suggestion" />
                <Label htmlFor="suggestion" className="flex items-center gap-2 cursor-pointer">
                  <Lightbulb className="w-4 h-4 text-warning" />
                  {t('complaints.suggestion')}
                </Label>
              </div>
            </RadioGroup>
          </div>

          {/* Category */}
          <div className="space-y-2">
            <Label htmlFor="category">{t('complaints.category')} *</Label>
            <Select onValueChange={(value) => setValue('category', value)}>
              <SelectTrigger>
                <SelectValue placeholder={language === 'ms' ? 'Pilih kategori' : 'Select category'} />
              </SelectTrigger>
              <SelectContent>
                {categories.map((cat) => (
                  <SelectItem key={cat.value} value={cat.value}>
                    {language === 'ms' ? cat.labelMs : cat.labelEn}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {errors.category && (
              <p className="text-sm text-destructive">{errors.category.message}</p>
            )}
          </div>

          {/* Priority - Only for complaints */}
          {selectedType === 'complaint' && (
            <div className="space-y-2">
              <Label>{language === 'ms' ? 'Keutamaan' : 'Priority'}</Label>
              <Select 
                defaultValue="normal"
                onValueChange={(value) => setValue('priority', value as any)}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="low">{language === 'ms' ? 'Rendah' : 'Low'}</SelectItem>
                  <SelectItem value="normal">{language === 'ms' ? 'Biasa' : 'Normal'}</SelectItem>
                  <SelectItem value="high">{language === 'ms' ? 'Tinggi' : 'High'}</SelectItem>
                  <SelectItem value="urgent">{language === 'ms' ? 'Segera' : 'Urgent'}</SelectItem>
                </SelectContent>
              </Select>
            </div>
          )}

          {/* Subject */}
          <div className="space-y-2">
            <Label htmlFor="subject">{t('complaints.subject')} *</Label>
            <Input
              id="subject"
              {...register('subject')}
              placeholder={language === 'ms' ? 'Tajuk ringkas aduan/cadangan' : 'Brief title of complaint/suggestion'}
              maxLength={200}
            />
            {errors.subject && (
              <p className="text-sm text-destructive">{errors.subject.message}</p>
            )}
          </div>

          {/* Description */}
          <div className="space-y-2">
            <Label htmlFor="description">{t('complaints.description')} *</Label>
            <Textarea
              id="description"
              {...register('description')}
              placeholder={language === 'ms' 
                ? 'Terangkan dengan jelas aduan atau cadangan anda...' 
                : 'Describe your complaint or suggestion clearly...'}
              rows={6}
              maxLength={2000}
            />
            {errors.description && (
              <p className="text-sm text-destructive">{errors.description.message}</p>
            )}
          </div>

          <Button type="submit" disabled={isSubmitting} className="w-full">
            {isSubmitting 
              ? (language === 'ms' ? 'Menghantar...' : 'Submitting...') 
              : t('common.submit')}
          </Button>
        </form>
      </CardContent>
    </Card>
  );
}
